json.id customer.id
json.firstname customer.first_name
json.lastname customer.last_name
json.title customer.title
json.email customer.email
json.phone customer.phone
json.address customer.address
json.city_town customer.city_town
json.post_code customer.post_code
json.created_at customer.created_at
