version: "2.1"
services:
  app:
    build: .
    image: "bfnz_dev"
    volumes:
      - ./:/app
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    user: ${USER_ID}:${GROUP_ID}
    working_dir: /app
    command: "bin/rails s -b 0.0.0.0"
    depends_on:
      - db
    environment:
      - DOCKERIZED=true

  db:
    image: "postgres:9.6"
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "3001:5432"
    environment:
      - POSTGRES_DB=bfnz_development
      - POSTGRES_USER=bfnz
      - POSTGRES_PASSWORD=secret

  firefox:
    image: selenium/standalone-firefox:3.141.59

volumes:
  db:
  bundle:
