# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#

TerritorialAuthority.destroy_all unless Rails.env.production?
[
 ["001","Far North District", :far_north],
 ["002","Whangarei District", :whangarei],
 ["003","Kaipara District", :kaipara],
 ["011","Thames-Coromandel District", 'thames-coromandel'],
 ["012","Hauraki District", :hauraki],
 ["013","Waikato District", :waikato],
 ["015","Matamata-Piako District", :matamata_piako],
 ["016","Hamilton City", :hamilton],
 ["017","Waipa District", :waipa],
 ["018","Otorohanga District", :otorohanga],
 ["019","South Waikato District", :south_waikato],
 ["020","Waitomo District", :waitomo],
 ["021","Taupo District", :taupo],
 ["022","Western Bay of Plenty District", :western_bop],
 ["023","Tauranga City", :tauranga],
 ["024","Rotorua District", :rotorua],
 ["025","Whakatane District", :whakatane],
 ["026","Kawerau District", :kawerau],
 ["027","Opotiki District", :opotiki],
 ["028","Gisborne District", :gisborne],
 ["029","Wairoa District", :wairoa],
 ["030","Hastings District", :hastings],
 ["031","Napier City", :napier],
 ["032","Central Hawke's Bay District", :hawkes_bay],
 ["033","New Plymouth District", :new_plymouth],
 ["034","Stratford District", :stratford],
 ["035","South Taranaki District", :south_taranaki],
 ["036","Ruapehu District", :ruapehu],
 ["037","Wanganui District", :wanganui],
 ["038","Rangitikei District", :rangitikei],
 ["039","Manawatu District", :manawatu],
 ["040","Palmerston North City", :palmerston_north],
 ["041","Tararua District", :tararua],
 ["042","Horowhenua District", :horowhenua],
 ["043","Kapiti Coast District", :kapiti_coast],
 ["044","Porirua City", :porirua],
 ["045","Upper Hutt City", :upper_hutt],
 ["046","Lower Hutt City", :lower_hutt],
 ["047","Wellington City", :wellington],
 ["048","Masterton District", :masterton],
 ["049","Carterton District", :carterton],
 ["050","South Wairarapa District", :south_wairarapa],
 ["051","Tasman District", :tasman],
 ["052","Nelson City", :nelson],
 ["053","Marlborough District", :marlborough],
 ["054","Kaikoura District", :kaikoura],
 ["055","Buller District", :buller],
 ["056","Grey District", :grey],
 ["057","Westland District", :westland],
 ["058","Hurunui District", :hurunui],
 ["059","Waimakariri District", :waimakariri],
 ["060","Christchurch City", :christchurch_city],
 ["062","Selwyn District", :selwyn],
 ["063","Ashburton District", :ashburton],
 ["064","Timaru District", :timaru],
 ["065","Mackenzie District", :mackenzie],
 ["066","Waimate District", :waimate],
 ["068","Waitaki District", :waitaki],
 ["069","Central Otago District", :central_otago],
 ["070","Queenstown-Lakes District", :queenstown_lakes],
 ["071","Dunedin City", :dunedin],
 ["072","Clutha District", :clutha],
 ["073","Southland District", :southland],
 ["074","Gore District", :gore],
 ["075","Invercargill City", :invercargill],
 ["076","Auckland", :auckland],
].each do |code, name, addressfinder_name|
  TerritorialAuthority.create!(code: code, name: name, addressfinder_name: addressfinder_name)
end
